server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: AraGakkiyui
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  security:
    jwt:
      key: jwt-key
      expire: 7
  data:
    redis:
      url: redis://@localhost:6379/0
      connect-timeout: 6000ms

#  mvc:
#    favicon:
#      enabled: false

#logging:
#  level:
#    root: INFO
#    com.example.UserService: INFO
#    com.example.JwtUtils: INFO