server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 00000
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  security:
    jwt:
      key: jwt-key
      expire: 1
    oauth2:
      client:
        registration:
          github:
              client-id: oooo
              client-secret: 11111
              scope:
                - read:user
                - user:email
              redirect-uri: "http://localhost:8080/login/oauth2/code/github"
              authorization-grant-type: authorization_code
              client-name: Github
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user


  data:
    redis:
      url: redis://@localhost:6379/0
      connect-timeout: 6000ms

#  mvc:
#    favicon:
#      enabled: false

#logging:
#  level:
#    root: INFO
#    com.example.UserService: INFO
#    com.example.JwtUtils: INFO
